apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-svc
  namespace: weather-app
  labels:
    app: weather
    app-tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
        app: weather
        app-tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend-deployment
  namespace: weather-app
  labels:
    app: weather
    app-tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: weather
        app-tier: frontend
  template:
    metadata:
      labels:
        app: weather
        app-tier: frontend
    spec:
      containers:
      - name: weather-frontend-container
        image: bartonjelles3/weather-frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: WEATHER_QUERY_ADDRESS
          value: "http://weather-query-svc.weather-app.svc.cluster.local:8081/weather_query"
