apiVersion: v1
kind: Service
metadata:
  name: weather-frontend-svc
  labels:
    app: weather
    app-tier: frontend
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
        app: weather
        app-tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-frontend-deployment
  labels:
    app: weather
    app-tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
        app: weather
        app-tier: frontend
  template:
    metadata:
      labels:
        app: weather
        app-tier: frontend
    spec:
      containers:
      - name: weather-frontend-container
        image: us-west1-docker.pkg.dev/weather-app-391906/docker-images/weather-frontend:1.0
        ports:
        - containerPort: 80
        env:
        - name: QUERY_SVC_ADDR
          value: "http://weather-query-svc"
        readinessProbe:
          httpGet:
            path: /readyz
            port: 80
          initialDelaySeconds: 10
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30