apiVersion: v1
kind: Service
metadata:
  name: weather-query-svc
  labels:
    app: weather
    app-tier: query
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
        app: weather
        app-tier: query
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-query-deployment
  labels:
    app: weather
    app-tier: query
spec:
  replicas: 1
  selector:
    matchLabels:
        app: weather
        app-tier: query
  template:
    metadata:
      labels:
        app: weather
        app-tier: query
    spec:
      containers:
      - name: weather-query-container
        image: us-west1-docker.pkg.dev/weather-app-391906/docker-images/weather-query:1.0
        ports:
        - containerPort: 80