apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-main
  namespace: infra
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: app
    server: {{ .Values.spec.destination.server }}
  project: app
  source:
    path: infra/charts/weather-app-main
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}