steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'flask_weather'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/proven-verve-376422/weather-app/flask-weather:$SHORT_SHA', '.']
    timeout: '120s'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/proven-verve-376422/weather-app/flask-weather:$SHORT_SHA']
    timeout: '120s'

# Update Kubernetes manifest with new image tag
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials weather-app --region us-central1 --project proven-verve-376422
        kubectl set image deployment/flask-weather flask-weather=us-central1-docker.pkg.dev/proven-verve-376422/weather-app/flask-weather:${SHORT_SHA} --record